use prelude::Day;

use crate::Solution;

static INPUT: &str = include_str!("input.txt");

#[test]
fn day_08() {
    let solution = Solution::new(INPUT);
    assert_eq!(376, solution.part1().unwrap());
    assert_eq!(1352, solution.part2().unwrap());
}

#[test]
fn example() {
    let solution = Solution::new(
        "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............",
    );
    assert_eq!(14, solution.part1().unwrap());
    assert_eq!(34, solution.part2().unwrap());
}
